extend-exclude = [
    ".ruff.toml",
    "ruff.toml",
    "src/domain_models/__init__.py",
    "src/domain_models/todo.py",
    "src/todo/__init__.py",
    "src/todo/cli.py",
    "src/todo/storage.py",
    "test.sh",
    "tests/e2e/test_cli.py",
    "tests/test_uat_cycle01.py",
    "tests/unit/test_domain_models.py",
    "tests/unit/test_storage.py"
]

[lint]
ignore = ["E902", "E", "F"]
